spring.application.name=MindProve

# Set the server port
server.port=8888

# Spring Data JPA configurations for database connection
spring.datasource.url=jdbc:mysql://localhost:3306/dbmind
spring.datasource.username=root
spring.datasource.password=root

# Optional: Driver class name (MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect